services :
  mariadb :
    env_file: .env
    container_name: mariadb
    restart : always
    expose:
      - "3306"
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile

  wordpress :  
    env_file: .env
    container_name: wordpress
    restart : always
    ports:
      - 9000:9000
    # depends-on : 
    #   - mariadb
      # - nginx
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    volumes :
      - db:/var/www/html

  nginx : 
    container_name: nginx
    restart : always
    ports :
      - 80:80
    build:
          context: requirements/nginx
          dockerfile: Dockerfile
    volumes :
      - db:/var/www/html

volumes : 
  db :